export const technicalVideos = [
  { url: 'https://www.youtube.com/embed/xWp-83KYkXs?si=ETs8dhYv0z_Zd-MZ' },
  { url: 'https://www.youtube.com/embed/X8cyx0RK4JY?si=7H55xUwvAREt30z4' },
  { url: 'https://www.youtube.com/embed/G5c6yIzwxlA?si=jFb72eCUyo07Wucm' },
  { url: 'https://www.youtube.com/embed/v1X7jQ0PFHg?si=hynlx8C3RSx3xXRB' },
]

export const twitterPosts = [
  '1782770731795054927',
  '1792767337713779154',
  '1786773482858315925',
  '1778651572098273641',
  '1797804207988482467',
  '1786214095072415878',
  '1789269745331794304',
  '1791133994891055408',
  '1785668169291718919',
  '1798287171276931355',
  '1791469499969146953',
  '1783842187291300123',
  '1773305755241713707',
  '1771594959575003184',
  '1786043246130651262',
  '1815310938595373549',
  '1810971713532051886',
]

export const communityCallVideos = [
  { url: 'https://www.youtube.com/embed/W08ShT6sjEg?si=A3q6cZ9yVxAqKPCA' },
  { url: 'https://www.youtube.com/embed/vtJrd1GGyRw?si=O7QoHcmkCyGHWV37' },
  { url: 'https://www.youtube.com/embed/-eUXFnaMknE?si=IeX472WrU9Uci2Gm' },
  { url: 'https://www.youtube.com/embed/0C0egTSeagA?si=u2Xhc-ZX1hSgmQhW' },
  { url: 'https://www.youtube.com/embed/fk2CCHgmKbU?si=XXAJdUm6afHIsYhr' },
  { url: 'https://www.youtube.com/embed/sULMQwEQiAo?si=GEAYhfdNyXKDMxZS' },
  { url: 'https://www.youtube.com/embed/y00WII8ninA?si=0dXYfBbIJ_knRNsT' },
]

export const generalVideos = [
  { url: 'https://www.youtube.com/embed/rT2ydAarNG8?si=SKBa4t5hMRQp7kX_' },
  { url: 'https://www.youtube.com/embed/-GLRrdwtoqg?si=DNLPMGlDRfWdm36q' },
  { url: 'https://www.youtube.com/embed/L4tBpW5u8WM?si=bd71NzfrJ9D0Y3bx' },
  { url: 'https://www.youtube.com/embed/wIvDCHZyr1E?si=9PGHscFT8j4LPIx4' },
]

export const substrateCourses = [
  {
    title: 'Substrate Course: NFT Blockchain',
    description: `Substrate is the primary blockchain SDK used by developers to create the parachains that make up the Polkadot network.`,
    url: 'https://github.com/openguild-labs/substrate-kitties',
    img: '/static/images/polkadot/workshops/SubstrateKitties.png',
    released: true,
  },
  {
    title: 'Substrate Course: Nominated Proof of Stake Blockchain',
    description: `Learn how to configure the nominated proof of stake mechanism to your Substrate-based blockchain`,
    url: 'https://github.com/openguild-labs/substrate-npos',
    img: '/static/images/polkadot/workshops/SubstrateNpos.png',
    released: true,
  },
  {
    title: 'Substrate Course: Delegated Proof of Stake Blockchain',
    description: `Delegated Proof of Stake (DPoS) is a blockchain consensus mechanism where network users vote and elect delegates to validate the next block.`,
    url: 'https://github.com/openguild-labs/substrate-dpos',
    img: '/static/images/polkadot/workshops/SubstrateDpos.webp',
    released: true,
  },
  {
    title: 'Substrate Course: Breakdown Moonbeam Architecture',
    description: `Moonbeam is a full Ethereum-like environment and works with industry-standard Ethereum tools, DApps, and protocols.`,
    url: 'https://github.com/openguild-labs/substrate-moonbeam',
    img: '/static/images/polkadot/workshops/SubstrateMoonbeam.webp',
    released: true,
  },
  {
    title: 'Substrate Course: EVM-compatible blockchain',
    description: `Learn how to build a Substrate-based blockchain with an ability to compile and execute EVM-compatible contracts.`,
    url: 'https://github.com/openguild-labs/substrate-evm',
    img: '/static/images/polkadot/workshops/SubstrateEvm.webp',
    released: false,
  },
]

export const courses = [
  ...substrateCourses,
  {
    title: 'Rust Programming Course: OpenRust',
    description: `Substrate is the primary blockchain SDK used by developers to create the parachains that make up the Polkadot network.`,
    url: 'https://github.com/openguild-labs/open-rust',
    img: '/static/images/polkadot/workshops/OpenRust.png',
    released: true,
  },
].sort((ca, cb) => (cb.released ? 1 : -1) - (ca.released ? 1 : -1))

export const workshops = [
  {
    title: 'Introduction to Polkadot SDK - Substrate',
    description: 'Framework to build blockchain with ease.',
    url: 'https://docs.google.com/presentation/d/111Oc9ugmJW984SjAYhlnD1cX51RpRgt5/edit?usp=sharing&ouid=114747115887247911480&rtpof=true&sd=true',
    img: '/static/images/polkadot/workshops/workshop-01.png',
    released: true,
  },
  {
    title: 'Blockchain Builder Tool: Substrate & OpStack',
    description: `Introducing the similarities and architecture of Substrate and OpStack.`,
    url: 'https://docs.google.com/presentation/d/1P4KHHwOQqmJDaXz2czjCU-F_mMe_U03xJEJGXlMEF4Y/edit?usp=sharing',
    img: '/static/images/polkadot/workshops/workshop-02.webp',
    released: true,
  },
  {
    title: 'Building Rust Production-Ready System',
    description: `Walk through key features of Rust and how it is applied in the real world scalable system`,
    url: 'https://docs.google.com/presentation/d/13ebc9cS-0CWTCUDC2V1pfuBQR5cXTRj1/edit?usp=sharing&ouid=114747115887247911480&rtpof=true&sd=true',
    img: '/static/images/polkadot/workshops/workshop-03.webp',
    released: true,
  },
  {
    title: 'In and Out of DePIN on Polkadot',
    description: `Exploring the in and out of the decentralized physical infrastructure network on Polkadot`,
    url: 'https://docs.google.com/presentation/d/1PHDHAzBbuMfue1z2XMzpa2sU9YJ1q0zc/edit?usp=sharing&ouid=114747115887247911480&rtpof=true&sd=true',
    img: '/static/images/polkadot/workshops/Community_Call_4.webp',
    released: true,
  },
  {
    title: 'Developing Rust Applications',
    description: `Introducing Rust language ecosystem and technical stack for building applications using Rust`,
    url: 'https://docs.google.com/presentation/d/1s0jqtgt3DYMfYU7k_gaNOLFR9vMo6rrjJULIak2KdMU/edit?usp=sharing',
    img: '/static/images/polkadot/workshops/workshop-05.png',
    released: true,
  },
  {
    title: 'JAM: Demystifying the evolution of Polkadot',
    description: `Jam introduces a decentralized hybrid system offering smart-contract functionality structured...`,
    url: 'https://docs.google.com/presentation/d/1g9WSTcpS3M1cM_lSSKdHak0s_dm_LVYB/edit?usp=sharing&ouid=114747115887247911480&rtpof=true&sd=true',
    img: '/static/images/polkadot/workshops/Community_Call_6.webp',
    released: true,
  },
  {
    title: 'From Personal Computer to Polkadot Ubiquitous Computing Engine',
    description: `Introducing history of the computing machine and how the next generation of computation is invented`,
    url: 'https://docs.google.com/presentation/d/1apZtV0p8cE_B0eT4KtLeVhQoR3Se81r0/edit?usp=sharing&ouid=114747115887247911480&rtpof=true&sd=true',
    img: '/static/images/polkadot/workshops/Community_Call_4.2.webp',
    released: true,
  },
  {
    title: 'Maximizing Polkadot Capabilities with POP network',
    description: `Introducing about the R0GUE team and their startup story behinds the invention of the POP network`,
    url: 'https://docs.google.com/presentation/d/1FQkUhO416KiPcMOa4aOfp8iKAoxKJpbACZ6-p315eMo/edit?usp=sharing',
    img: '/static/images/polkadot/workshops/Community_Call_10.webp',
    released: true,
  },
  {
    title: 'Getting Started with Polkadot SDK',
    description: `Introducing the powerful Polkadot SDK for developing a blockchain with speed and security.`,
    url: 'https://docs.google.com/presentation/d/1qH6SvWcueV2XglbVSiB3abXnBEQS9aE-AkYN4qB1He8/edit?usp=sharing',
    img: '/static/images/polkadot/workshops/Community_Call_13.webp',
    released: true,
  },
  {
    title: 'Demystifying the workflow of Polkadot decentralized applications with Dedot',
    description:
      'A deep dive into Dedot, exploring the workflow of building decentralized applications on Polkadot.',
    url: 'https://docs.google.com/presentation/d/15LgOETDplI34M1NnU5v7Hs-izrUdoDaiaEeRGdNCSKk/edit?usp=sharing',
    released: true,
  },
  {
    title: 'Breaking down the Polkadot SDK source code',
    description:
      'An analysis of Polkadot SDK source code, providing insights into its architecture and functionality.',
    url: 'https://docs.google.com/presentation/d/1bLQfpPXc268k61Q5eYTeTOodMJxwfFnXt8ZrIpoMO8w/edit#slide=id.p',
    released: true,
  },
  {
    title: 'How Polkadot empowers cross-chain decentralized finance',
    description:
      'An exploration of how Polkadot facilitates decentralized finance across multiple blockchains.',
    url: 'https://docs.google.com/presentation/d/1xOa3YngT5iH-WMDHrJ8H4RinYP1Pzr5bqjIYhutbZfc/edit?usp=sharing',
    released: true,
  },
  {
    title: 'Peer-to-peer Network and Why it is the END GAME of the Internet?',
    description:
      'An introduction to peer-to-peer networks and why they represent the future of internet infrastructure.',
    url: 'https://docs.google.com/presentation/d/11GMPMg0fIM2GwP4GKVbShkgbhEPvsWR-tIUfK0gfbYM/edit?usp=sharing',
    released: true,
  },
  {
    title: 'The Next Generation Of The Internet - Web 3.0',
    description:
      'A comprehensive guide to Web 3.0 and its potential to revolutionize the internet.',
    url: 'https://docs.google.com/presentation/d/1efPd-PxcdC3nPimASNiN744EJWIwqp7Y/edit?usp=sharing&ouid=114747115887247911480&rtpof=true&sd=true',
    released: true,
  },
  {
    title: 'Building a decentralized applications on Polkadot',
    description:
      'A step-by-step guide on building decentralized applications (dApps) using Polkadot.',
    url: 'https://docs.google.com/presentation/d/1mWR4Y75-IFg3gtnN7X_u_IJzIbtdG87g/edit?usp=sharing&ouid=114747115887247911480&rtpof=true&sd=true',
    released: true,
  },
  {
    title: 'Upgradeable Proxy - Techniques for Creating and Managing Upgradeable Contracts',
    description:
      'Learn about techniques for creating and managing upgradeable smart contracts on Polkadot.',
    url: 'https://docs.google.com/presentation/d/1LL2_CPGvbGfhhMpwKm_VzLZeDxFVahPph5cM37QUftI/edit?usp=drive_link',
    released: true,
  },
  {
    title: 'Demystifying Vara Network: Inftrastructure for Secure Smart Contract Development',
    description:
      'An overview of Vara Network, designed to support secure and efficient smart contract development.',
    url: 'https://docs.google.com/presentation/d/1pmpZ6zqegfIjD7UngRbN1dxFwktTMmuCfABwfNNTcug/edit?usp=drive_link',
    released: true,
  },
  {
    title: 'Hyperbridge - Cryptographically secure cross-chain interoperability',
    description:
      'Explaining Hyperbridge, the cryptographic solution enabling secure cross-chain interoperability in the Polkadot ecosystem.',
    url: 'https://docs.google.com/presentation/d/1hT3zc-Zmv6S0uKT4W-0SxBBjjqtIwwGj/edit?usp=drive_link&ouid=114747115887247911480&rtpof=true&sd=true',
    released: true,
  },
  {
    title: 'Unlock the power of appchain infrastructure with Tanssi Network',
    description:
      'Explore how Tanssi Network provides appchain infrastructure and its role in the decentralized ecosystem.',
    url: 'https://docs.google.com/presentation/d/1XmOwA7KidoE7MDzn_SvVJAtlFKjKH5x-i_Hnqa4Hb70/edit?usp=drive_link',
    released: true,
  },
  {
    title: 'Seamless Polkadot development with POP',
    description: 'A guide to developing on Polkadot seamlessly using the POP network.',
    url: 'https://docs.google.com/presentation/d/1jwd4BTvaaMNDR5a8yYkp-S5baORXVMrkc8rMe48mqi4/edit?usp=drive_link',
    released: true,
  },
].sort((ca, cb) => (cb.title > ca.title ? -1 : 1))

export const researchArticles = [
  {
    title: 'Relaychain Hybrid Consensus',
    description:
      'Learning about hybrid consensus in Relaychain and why it is important to the Polkadot protocol?',
    url: '1809203505649037391',
    img: '/static/images/polkadot/articles/research-article-1.jpeg',
    released: true,
  },
  {
    title: 'Breakdown the sharded network design of Polkadot',
    description: `Discover deeper into how Polkadot is designed to be a fragmented network, or we can say a multi-chain, multi-sharded network as well.`,
    url: 'https://x.com/chungquantin/status/1809864276850704882',
    img: '/static/images/polkadot/articles/research-article-2.jpg',
    released: true,
  },
  {
    title: 'Breakdown the Tanssi network architecture',
    description: `Discover deeper into how Tanssi network powers AppChain deployment with their infrastructure.`,
    url: 'https://x.com/openguildwtf/status/1831633260545454471',
    img: '/static/images/polkadot/articles/research-article-3.jpeg',
    released: true,
  },
].sort((ca, cb) => (cb.released ? 1 : -1) - (ca.released ? 1 : -1))

export const inkTutorials = [
  {
    title: 'OpenHack Workshop - ink! Starter',
    description: 'Getting started with ink! smart contract development.',
    url: 'https://github.com/openguild-labs/open-hack-ink-starter',
    img: '/static/images/polkadot/workshops/OpenHack_inkStarter.png',
    released: true,
  },
  {
    title: 'OpenHack Workshop - ink! Advanced',
    description: 'Learning more advanced concepts in ink! related to token standards and more.',
    url: 'https://github.com/openguild-labs/open-hack-ink-advanced',
    img: '/static/images/polkadot/workshops/OpenHack_inkAdvanced.png',
    released: true,
  },
  {
    title: 'OpenHack Workshop - Dedot',
    description:
      'Introduction to the client library Dedot to interact with Substrate-based nodes and ink! smart contract language.',
    url: 'https://github.com/openguild-labs/open-hack-dedot',
    img: '/static/images/polkadot/workshops/OpenHack_Dedot.png',
    released: true,
  },
]

export const bootcampPolkadotSdkVideos = [
  {
    title: 'Open Polkadot Bootcamp 2025 - Introduce the Developer Bootcamp',
    description:
      'In this series, Tin Chung will take you step-by-step through the Polkadot SDK, empowering you to build scalable dApps and parachains on the Polkadot ecosystem.',
    url: 'https://www.youtube.com/embed/JEvsI41bhUg?si=LwTpbT7-1B7HkEtc',
  },
  {
    title: 'Open Polkadot Bootcamp 2025 - Introduce to Polkadot & Polkadot SDK [Section 1]',
    description:
      'In this video, we’ll introduce you to the Polkadot network, its revolutionary blockchain architecture, and the Polkadot SDK that powers developers to build scalable, interoperable blockchains',
    url: 'https://www.youtube.com/embed/h-a0_i5WomA?si=m96gxM6tEoftEAvd',
  },
  {
    title: 'Open Polkadot Bootcamp 2025 - Create a blockchain with Polkadot SDK [Section 2]',
    description:
      'In this video, we’ll guide you through creating a blockchain from scratch using the Polkadot SDK. You’ll learn the fundamentals of Substrate-based development and how to customize your chain for specific use cases.',
    url: 'https://www.youtube.com/embed/5G6YazQnPI4?si=3zQ_m-vVtDs69jQW',
  },
  {
    title: 'Open Polkadot Bootcamp 2025 - Build a State Machine from scratch [Section 3]',
    description:
      'In this tutorial, we’ll walk you through building a state machine—the foundation of any blockchain—entirely from scratch. Learn how states transition and how to implement efficient and secure state management.',
    url: 'https://www.youtube.com/embed/QettrQIXA1c?si=KvHq27HvdbSGkT9Y',
  },
  {
    title: 'Open Polkadot Bootcamp 2025 - Adding a custom logic to a Runtime [Section 4 | Part 1]',
    description:
      'This video explores how to add custom logic to your blockchain runtime using the Polkadot SDK. Whether you’re designing a dApp or a parachain, this tutorial will show you how to tailor your chain to meet specific needs.',
    url: 'https://www.youtube.com/embed/diMgOaIYo-s?si=WGfx1tReH26jKGHn',
  },
  {
    title: 'Open Polkadot Bootcamp 2025 - Common Runtime Modules [Section 4 | Part 2]',
    description:
      'This video provides an overview of commonly used runtime modules and their functionalities. From account management to governance, you’ll learn how to utilize these building blocks to accelerate your blockchain development.',
    url: 'https://www.youtube.com/embed/zCIvp_P5atY?si=uF-AeIIA-4nZx9KA',
  },
  {
    title:
      'Open Polkadot Bootcamp 2025 - Substrate Storage Abstractions & Common Storage [Section 4 | Part 3]',
    description:
      'In this video, we break down the storage abstraction in Substrate and explore common storage types. Learn how to store and manage on-chain data efficiently and securely for your dApps or parachains.',
    url: 'https://www.youtube.com/embed/Fco3oc1JuoI?si=BzT175YUSt_3O_-0',
  },
  {
    title: 'Open Polkadot Bootcamp 2025 - Hooks (Polkadot SDK) [Section 4 | Part 4]',
    description:
      'In this tutorial, we explain what hooks are, how they work, and how to implement them for lifecycle management in your runtime modules.',
    url: 'https://www.youtube.com/embed/jGLb5Jlh8WI?si=lfOeN1x2N0-gj9Bl',
  },
  {
    title: 'Open Polkadot Bootcamp 2025 - Runtime API (Polkadot SDK) [Section 4 | Part 5]',
    description:
      'This video focuses on exposing logic from your runtime to external nodes. Learn how Runtime APIs work and how to use them to build efficient and interactive blockchain solutions.',
    url: 'https://www.youtube.com/embed/BTz39Kzlv-U?si=qxXAhMB3jD99QJJO',
  },
  {
    title:
      'Open Polkadot Bootcamp - Interact with Substrate node on PolkadotJS Apps [Section 5 | Part 1]',
    description:
      "This tutorial demonstrates how to interact with a Substrate node using PolkadotJS Apps. You’ll learn how to test transactions, query storage, and deploy smart contracts via Polkadot's web interface.",
    url: 'https://www.youtube.com/embed/uMaSEWajHT0?si=-MJ20uPmy58c1Bl_',
  },
  {
    title: 'Open Polkadot Bootcamp - Mainnet, Testnet and Canary Network [Section 5 | Part 2]',
    description:
      'This video explains the purpose of each environment and provides best practices for deploying and testing your blockchain.',
    url: 'https://www.youtube.com/embed/HL0Y0vseNuE?si=UkwnoYPIX43G8sYP',
  },

  {
    title: 'Open Polkadot Bootcamp - Bump a Polkadot SDK version [Section 6]',
    description:
      'This tutorial covers how to bump a Polkadot SDK version, ensuring your project benefits from the latest features, security updates, and optimizations.',
    url: 'https://www.youtube.com/embed/6nhIZmE1Nck?si=jkU0dNIvUaLhJ1uR',
  },
  {
    title: 'Open Polkadot Bootcamp - Path of Parachain block breakdown [Section 7]',
    description:
      'In this video, we break down the path of a parachain block, explaining how data flows through the network and ensuring security, validation, and consensus.',
    url: 'https://www.youtube.com/embed/qv_kCjFvq8k?si=fV5lZKwZcn-SWLM2',
  },
  {
    title: 'Open Polkadot Bootcamp - Polkadot SDK - Introduce to Cumulus [Section 8]',
    description:
      'In this video, we’ll introduce you to the Cumulus framework, its architecture, and how it connects parachains to the relay chain for seamless interoperability.',
    url: 'https://www.youtube.com/embed/97qt3AdZZnQ?si=CR4WEIuz1bqyJRHa',
  },
  {
    title: 'Open Polkadot Bootcamp - Connect A Parachain To Relaychain Network [Section 9]',
    description:
      'This tutorial provides a step-by-step guide on configuring and registering your parachain for full network integration.',
    url: 'https://www.youtube.com/embed/1epyfBorXI8?si=TnsBICT11xdTWLso',
  },
  {
    title:
      'Open Polkadot Bootcamp - Introduction to XCM, Transport Protocols & XCVM [Section 10 | Part 1]',
    description:
      'This video explains the basics of XCM, the transport protocol, and XCVM, enabling seamless communication and interactions across blockchains.',
    url: 'https://www.youtube.com/embed/4dcqMtPOlbk?si=aIeqBVb91bSLChs4',
  },
  {
    title:
      'Open Polkadot Bootcamp - XCM Fundamentals with Locations & Assets [Section 10 | Part 2]',
    description:
      'In this video, we explore location concepts, asset transfers, and the fundamentals of cross-chain messaging within the Polkadot ecosystem.',
    url: 'https://www.youtube.com/embed/bd-vz5E2Vyk?si=I5qDHMHW_vnCBV50',
  },
  {
    title: 'Open Polkadot Bootcamp - Teleport, Transfers and Transact [Section 10 Part 3]',
    description:
      'This tutorial demonstrates how to use Teleport, Transfer, and Transact functions to move assets across chains and execute transactions securely and efficiently.',
    url: 'https://www.youtube.com/embed/GQU3EXX8v4Q?si=wKJ2iaSU4YdhKmE3',
  },
]

export const bootcampSolidityOnPolkaVmVideos = [
  {
    title: 'Open Polkadot Bootcamp 2025 - Introduce PolkaVM',
    description:
      'In this video, we introduce you to PolkaVM, a revolutionary smart contract platform built on RISC-V. Learn how PolkaVM empowers EVM developers to build efficient, scalable, and interoperable smart contracts on Polkadot.',
    url: 'https://www.youtube.com/embed/EFTMgkqZDNE?si=xUbT4b91qgqUQXAR',
  },
  {
    title: 'Open Polkadot Bootcamp 2025 - PolkaVM - Getting Started [Section 1 | Part 1]',
    description:
      'In this tutorial, we’ll set up the tools and environment needed for developing and deploying smart contracts on PolkaVM. By the end, you’ll have everything ready to start building on this innovative platform.',
    url: 'https://www.youtube.com/embed/01Day_18Eio?si=RifGFW_WVNhlqq4E',
  },
  {
    title:
      'Open Polkadot Bootcamp 2025 - PolkaVM - Structure of a Solidity file - [Section 1 | Part 2]',
    description:
      'This video breaks down the anatomy of a Solidity file, including its essential components, and shows how PolkaVM adapts Solidity for RISC-V-based execution.',
    url: 'https://www.youtube.com/embed/b61wDEsjxpE?si=YXfzkP7JXUUFOkt2',
  },
  {
    title: 'Open Polkadot Bootcamp 2025 - PolkaVM - Contract structure - [Section 1 | Part 3]',
    url: 'https://www.youtube.com/embed/DGa6EcMsoe8?si=xApgsuysoB-E9iAF',
    description:
      'In this tutorial, we’ll explore the overall structure of a smart contract in PolkaVM, including state variables, functions, and modifiers. Gain a solid foundation for building complex and secure contracts.',
  },
  {
    title: 'Open Polkadot Bootcamp 2025 - PolkaVM - Simple Storage [Section 2]',
    url: 'https://www.youtube.com/embed/QQyOH0eivTc?si=z7a4zMbkO6iEULgT',
    description:
      'In this video, we’ll create a basic storage contract to demonstrate how PolkaVM handles state changes and persistent data on the blockchain.',
  },
  {
    title: 'Open Polkadot Bootcamp 2025 - PolkaVM - Value Types [Section 2 | Part 2]',
    url: 'https://www.youtube.com/embed/iYgPpoxXEYw?si=xe4JfBtRVkbqj2Ux',
    description:
      'This tutorial covers common value types like integers, booleans, and addresses, explaining how they’re used and managed within the PolkaVM framework.',
  },
  {
    title: 'Open Polkadot Bootcamp 2025 - PolkaVM - Reference Types [Section 2 | Part 3]',
    url: 'https://www.youtube.com/embed/oYcc_ZWTsic?si=_QjPolEjwr0BmhEA',
    description:
      'In this video, we’ll discuss arrays, structs, and other reference types, showing how to store and manipulate complex data structures in smart contracts.',
  },
  {
    title: 'Open Polkadot Bootcamp 2025 - PolkaVM - Mapping Types - [Section 2 | Part 4]',
    url: 'https://www.youtube.com/embed/lhgvmmMbDkc?si=MfHkBnEDUKYMaiCX',
    description:
      'This tutorial demonstrates how mappings work in PolkaVM, their syntax, and best practices for organizing and retrieving data in your contracts.',
  },
  {
    title: 'Open Polkadot Bootcamp 2025 - PolkaVM - Advanced Storage [Section 3]',
    url: 'https://www.youtube.com/embed/J2Zi44l5LwA?si=kd3AMx94910yRIwl',
    description:
      'In this video, we’ll explore advanced storage concepts in PolkaVM, including dynamic data handling and optimization techniques for more efficient smart contracts.',
  },
  {
    title: 'Open Polkadot Bootcamp 2025 - PolkaVM - Units [Section 3 | Part 2]',
    url: 'https://www.youtube.com/embed/91yjmtDWUok?si=WiDxXgPy80814_L1',
    description:
      'This tutorial explains how to work with time units, currency denominations, and other measurement systems within smart contracts.',
  },
  {
    title: 'Open Polkadot Bootcamp 2025 - PolkaVM - Global Variables [Section 3 | Part 3]',
    url: 'https://www.youtube.com/embed/ZHA1tt1qYB0?si=aAq1Cbp4mt6a2t4I',
    description:
      'In this video, we’ll cover essential global variables like msg.sender and block.timestamp, demonstrating how they’re used to build dynamic and secure contracts.',
  },
  {
    title:
      'Open Polkadot Bootcamp 2025 - PolkaVM - Expression and Control Structures - [Section 3 | Part 4]',
    url: 'https://www.youtube.com/embed/UdIxAO_Jha8?si=ax5xEh3C-ooaft2Q',
    description:
      'This tutorial teaches you how to use if-else statements, loops, and other control structures to create logic for your smart contracts in PolkaVM.',
  },
]

export const rustTutorials = [
  {
    title: 'OpenHack Workshop - Rust Starter',
    description:
      'Introduce Rust programming language and help the participants to get familiar with the language.',
    url: 'https://github.com/openguild-labs/open-hack-rust-starter',
    img: '/static/images/polkadot/workshops/OpenHack_RustStarter.png',
    released: true,
  },
]

export const substrateTutorials = [
  {
    title: 'OpenHack Workshop - Substrate Starter',
    description:
      'Introduce Polkadot SDK - Substrate and help the participants to get familiar with the blockchain builder tool.',
    url: 'https://github.com/openguild-labs/open-hack-substrate-starter',
    img: '/static/images/polkadot/workshops/OpenHack_SubstrateStarter.png',
    released: true,
  },
]

export const technicalActivityProjects = [
  ...substrateTutorials,
  ...rustTutorials,
  ...inkTutorials,
].sort((ca, cb) => (cb.released ? 1 : -1) - (ca.released ? 1 : -1))

export const learningResources = [
  {
    'Course Name': 'Open Rust Bootcamp',
    Status: 'Not started',
    'Third-party source': 'No',
    Link: 'https://github.com/openguild-labs/open-rust',
    Category: 'Course',
    Level: 'Beginner',
    Language: 'English',
    Source: 'OpenGuild',
    'Bundle Name': 'Rust Course Bundle',
  },
  {
    'Course Name': 'ink! Official Documentation',
    Status: 'In progress',
    'Third-party source': 'Yes',
    Link: 'https://use.ink/',
    Category: 'Documentation',
    Level: 'Beginner',
    Language: 'English',
    Source: 'Parity Technologies',
    'Bundle Name': '',
  },
  {
    'Course Name': 'Polkadot Blockchain Academy Book',
    Status: 'Done',
    'Third-party source': 'Yes',
    Link: 'https://polkadot-blockchain-academy.github.io/pba-book/',
    Category: 'Educational Program',
    Level: 'Beginner',
    Language: 'English',
    Source: 'Polkadot Blockchain Academy',
    'Bundle Name': '',
  },
  {
    'Course Name': 'Polkadot Blockchain Academy Slides',
    Status: 'Done',
    'Third-party source': 'Yes',
    Link: 'https://polkadot-blockchain-academy.github.io/pba-content/',
    Category: 'Educational Program',
    Level: 'Beginner',
    Language: 'English',
    Source: 'Polkadot Blockchain Academy',
    'Bundle Name': '',
  },
  {
    'Course Name': 'Dotcodeschool - Rust State Machine: Basic Concepts for Blockchain Development',
    Status: 'Done',
    'Third-party source': 'Yes',
    Link: 'https://dotcodeschool.com/courses/rust-state-machine',
    Category: 'Course',
    Level: 'Beginner',
    Language: 'English',
    Source: 'Dotcodeschool',
    'Bundle Name': '',
  },
  {
    'Course Name': 'Dotcodeschool - Build your own DEX',
    Status: 'Done',
    'Third-party source': 'Yes',
    Link: 'https://dotcodeschool.com/courses/build-your-own-dex',
    Category: 'Course',
    Level: 'Beginner',
    Language: 'English',
    Source: 'Dotcodeschool',
    'Bundle Name': '',
  },
  {
    'Course Name': 'Dotcodeschool - Substrate Kitties: Build Your Own NFT Marketplace',
    Status: 'Done',
    'Third-party source': 'Yes',
    Link: 'https://dotcodeschool.com/courses/substrate-kitties',
    Category: 'Course',
    Level: 'Beginner',
    Language: 'English',
    Source: 'Dotcodeschool',
    'Bundle Name': '',
  },
  {
    'Course Name': 'Polkadot SDK là gì?',
    Status: 'Done',
    'Third-party source': 'No',
    Link: 'https://openguild.wtf/blog/polkadot/polkadot-sdk-la-gi',
    Category: 'Technical Blog',
    Level: 'Beginner',
    Language: 'Vietnamese',
    Source: 'OpenGuild',
    'Bundle Name': 'Substrate Course Bundle',
  },
  {
    'Course Name': 'Polkadot Guide: Chạy Substrate Node trên máy tính của bạn',
    Status: 'Done',
    'Third-party source': 'No',
    Link: 'https://openguild.wtf/blog/polkadot/polkadot-guide-chay-local-substrate-node',
    Category: 'Technical Blog',
    Level: 'Beginner',
    Language: 'Vietnamese',
    Source: 'OpenGuild',
    'Bundle Name': 'Substrate Course Bundle',
  },
  {
    'Course Name': 'Polkadot Guide: Giả lập mạng Substrate',
    Status: 'Done',
    'Third-party source': 'No',
    Link: 'https://openguild.wtf/blog/polkadot/polkadot-guide-gia-lap-mang-substrate',
    Category: 'Technical Blog',
    Level: 'Beginner',
    Language: 'Vietnamese',
    Source: 'OpenGuild',
    'Bundle Name': 'Substrate Course Bundle',
  },
  {
    'Course Name': 'Polkadot Guide: Pallet là gì?',
    Status: 'Done',
    'Third-party source': 'No',
    Link: 'https://openguild.wtf/blog/polkadot/polkadot-guide-pallet-la-gi',
    Category: 'Technical Blog',
    Level: 'Beginner',
    Language: 'Vietnamese',
    Source: 'OpenGuild',
    'Bundle Name': 'Substrate Course Bundle',
  },
  {
    'Course Name': 'Code Breakdown - FRAME Pallet',
    Status: 'Done',
    'Third-party source': 'No',
    Link: 'https://openguild.wtf/blog/polkadot/code-breakdown-pallet-template',
    Category: 'Technical Blog',
    Level: 'Beginner',
    Language: 'Vietnamese',
    Source: 'OpenGuild',
    'Bundle Name': 'Substrate Course Bundle',
  },
  {
    'Course Name': 'VBI Academy x OpenGuild - Polkadot Bootcamp',
    Status: 'In progress',
    'Third-party source': 'Yes',
    Link: 'https://openedu101.com/en/bootcamps/polkadot-bootcamp',
    Category: 'Educational Program',
    Level: 'Beginner',
    Language: 'Vietnamese',
    Source: 'VBI Academy',
    'Bundle Name': '',
  },
  {
    'Course Name': 'Polkadot Study - Interactive Substrate Tutorial',
    Status: 'Done',
    'Third-party source': 'Yes',
    Link: 'https://polkadot.study/tutorials/interactive-substrate-tutorials-rusty-crewmates/',
    Category: 'Course',
    Level: 'Beginner',
    Language: 'English',
    Source: 'Polkadot Study',
    'Bundle Name': '',
  },
  {
    'Course Name': 'Polkadot ink! Smart Contract Tutorial',
    Status: 'Done',
    'Third-party source': 'No',
    Link: 'https://openguild.wtf/blog/polkadot/polkadot-ink-smart-contract-tutorial',
    Category: 'Technical Blog',
    Level: 'Beginner',
    Language: 'English',
    Source: 'OpenGuild',
    'Bundle Name': 'Ink Course Bundle',
  },
  {
    'Course Name': 'Basic Wallet with Polkadot.js API and React with TypeScript.',
    Status: 'Done',
    'Third-party source': 'Yes',
    Link: 'https://polkadot.study/tutorials/wallet-with-polkadot-js-and-react-with-typescript/intro',
    Category: 'Course',
    Level: 'Beginner',
    Language: 'English',
    Source: 'Polkadot Study',
    'Bundle Name': '',
  },
  {
    'Course Name': 'Polkadot Development Roadmap',
    Status: 'Done',
    'Third-party source': 'No',
    Link: 'https://roadmap.sh/r/polkadot-development-roadmap',
    Category: 'Aggregated Resource',
    Level: 'Beginner',
    Language: 'English',
    Source: 'OpenGuild',
    'Bundle Name': 'Substrate Course Bundle',
  },
  {
    'Course Name': 'Polkadot Knowledge Map',
    Status: 'Done',
    'Third-party source': 'No',
    Link: 'https://github.com/openguild-labs/polkadot-knowledge-map',
    Category: 'Aggregated Resource',
    Level: 'Beginner',
    Language: 'English',
    Source: 'OpenGuild',
    'Bundle Name': 'Substrate Course Bundle',
  },
  {
    'Course Name': 'Open Hack Pallet Starter',
    Status: 'Done',
    'Third-party source': 'No',
    Link: 'https://github.com/openguild-labs/open-hack-pallet-starter',
    Category: 'Open Hack Module',
    Level: 'Beginner',
    Language: 'Vietnamese',
    Source: 'OpenGuild',
    'Bundle Name': 'Substrate Course Bundle',
  },
  {
    'Course Name': 'Open Hack Rust Starter',
    Status: 'Done',
    'Third-party source': 'No',
    Link: 'https://github.com/openguild-labs/open-hack-rust-starter',
    Category: 'Open Hack Module',
    Level: 'Beginner',
    Language: 'English',
    Source: 'OpenGuild',
    'Bundle Name': 'Rust Course Bundle',
  },
  {
    'Course Name': 'Open Hack Substrate Starter',
    Status: 'Done',
    'Third-party source': 'No',
    Link: 'https://github.com/openguild-labs/open-hack-substrate-starter',
    Category: 'Open Hack Module',
    Level: 'Beginner',
    Language: 'English',
    Source: 'OpenGuild',
    'Bundle Name': 'Substrate Course Bundle',
  },
  {
    'Course Name': 'Open Hack Dedot',
    Status: 'Done',
    'Third-party source': 'No',
    Link: 'https://github.com/openguild-labs/open-hack-dedot',
    Category: 'Open Hack Module',
    Level: 'Beginner',
    Language: 'English',
    Source: 'OpenGuild',
    'Bundle Name': 'Dedot Course Bundle',
  },
  {
    'Course Name': 'Open Hack ink! Starter',
    Status: 'Done',
    'Third-party source': 'No',
    Link: 'https://github.com/openguild-labs/open-hack-ink-starter',
    Category: 'Open Hack Module',
    Level: 'Beginner',
    Language: 'English',
    Source: 'OpenGuild',
    'Bundle Name': 'Ink Course Bundle',
  },
  {
    'Course Name': 'Substrate Graph Benchmarks',
    Status: 'Done',
    'Third-party source': 'Yes',
    Link: 'https://www.shawntabrizi.com/substrate-graph-benchmarks/docs/#/',
    Category: 'Documentation',
    Level: 'Intermediate',
    Language: 'English',
    Source: 'Shawn Tabrizi',
    'Bundle Name': 'Substrate Course Bundle',
  },
  {
    'Course Name': 'Substrate Runtime Storage Migrations',
    Status: 'Done',
    'Third-party source': 'Yes',
    Link: 'https://www.blog.nodrama.io/substrate-runtime-storage-migrations/',
    Category: 'Technical Blog',
    Level: 'Intermediate',
    Language: 'English',
    Source: 'NoDrama',
    'Bundle Name': '',
  },
  {
    'Course Name': 'Papermoon Ecosystem Docs - Zombinet',
    Status: 'In progress',
    'Third-party source': 'Yes',
    Link: 'https://papermoonio.github.io/polkadot-ecosystem-docs-draft/dev-tools/zombienet/',
    Category: 'Documentation',
    Level: 'Intermediate',
    Language: 'English',
    Source: 'Papermoon',
    'Bundle Name': '',
  },
  {
    'Course Name': 'Papermoon Ecosystem Docs - Chopstick',
    Status: 'In progress',
    'Third-party source': 'Yes',
    Link: 'https://papermoonio.github.io/polkadot-ecosystem-docs-draft/dev-tools/chopsticks/overview/',
    Category: 'Documentation',
    Level: 'Intermediate',
    Language: 'English',
    Source: 'Papermoon',
    'Bundle Name': '',
  },
  {
    'Course Name': 'Relaychain Hybrid Consensus',
    Status: 'Done',
    'Third-party source': 'No',
    Link: 'https://x.com/openguildwtf/status/1809203505649037391',
    Category: 'Technical Blog',
    Level: 'Intermediate',
    Language: 'English',
    Source: 'OpenGuild',
    'Bundle Name': 'Substrate Course Bundle',
  },
  {
    'Course Name': 'Breakdown the sharded network design of Polkadot',
    Status: 'Done',
    'Third-party source': 'No',
    Link: 'https://x.com/chungquantin/status/1809864276850704882',
    Category: 'Technical Blog',
    Level: 'Intermediate',
    Language: 'English',
    Source: 'OpenGuild',
    'Bundle Name': 'Substrate Course Bundle',
  },
  {
    'Course Name': 'Code Breakdown - Substrate Node',
    Status: 'Done',
    'Third-party source': 'No',
    Link: 'https://openguild.wtf/blog/polkadot/code-breakdown-substrate-node',
    Category: 'Technical Blog',
    Level: 'Intermediate',
    Language: 'Vietnamese',
    Source: 'OpenGuild',
    'Bundle Name': 'Substrate Course Bundle',
  },
  {
    'Course Name': 'Code Breakdown - Substrate P2P Networking',
    Status: 'Done',
    'Third-party source': 'No',
    Link: 'https://openguild.wtf/blog/polkadot/code-breakdown-substrate-p2p-networking',
    Category: 'Technical Blog',
    Level: 'Intermediate',
    Language: 'Vietnamese',
    Source: 'OpenGuild',
    'Bundle Name': 'Substrate Course Bundle',
  },
  {
    'Course Name': 'Polkadot Study - Substrate In Bits',
    Status: 'Done',
    'Third-party source': 'Yes',
    Link: 'https://polkadot.study/tutorials/substrate-in-bits',
    Category: 'Course',
    Level: 'Intermediate',
    Language: 'English',
    Source: 'Polkadot Study',
    'Bundle Name': '',
  },
  {
    'Course Name': 'Polkadot Study - Tokengated Website with polkadot.js and next-auth',
    Status: 'Done',
    'Third-party source': 'Yes',
    Link: 'https://polkadot.study/tutorials/tokengated-polkadot-next-js/intro',
    Category: 'Course',
    Level: 'Intermediate',
    Language: 'English',
    Source: 'Polkadot Study',
    'Bundle Name': '',
  },
  {
    'Course Name':
      'Polkadot Study - How to implement decentralized exchange in ink! smart contract language',
    Status: 'Done',
    'Third-party source': 'Yes',
    Link: 'https://polkadot.study/tutorials/decentralized-exchange-ink/introduction',
    Category: 'Course',
    Level: 'Intermediate',
    Language: 'English',
    Source: 'Polkadot Study',
    'Bundle Name': '',
  },
  {
    'Course Name': 'OpenGuild’s Coding Session: Rust State Machine',
    Status: 'Done',
    'Third-party source': 'No',
    Link: 'https://www.youtube.com/watch?v=xWp-83KYkXs',
    Category: 'Tutorial Video & Livestream',
    Level: 'Intermediate',
    Language: 'English',
    Source: 'OpenGuild',
    'Bundle Name': 'Substrate Course Bundle',
  },
  {
    'Course Name': "OpenGuild's Coding Session: Implementing a Merkle Tree",
    Status: 'Done',
    'Third-party source': 'No',
    Link: 'https://www.youtube.com/watch?v=X8cyx0RK4JY&t=1689s',
    Category: 'Tutorial Video & Livestream',
    Level: 'Intermediate',
    Language: 'English',
    Source: 'OpenGuild',
    'Bundle Name': 'Substrate Course Bundle',
  },
  {
    'Course Name': 'Substrate Bitcoin',
    Status: 'Not started',
    'Third-party source': 'No',
    Link: 'https://github.com/openguild-labs/substrate-bitcoin',
    Category: 'Course',
    Level: 'Intermediate',
    Language: 'English',
    Source: 'OpenGuild',
    'Bundle Name': 'Substrate Course Bundle',
  },
  {
    'Course Name': 'Open Hack XCM',
    Status: 'Not started',
    'Third-party source': 'No',
    Link: 'https://github.com/openguild-labs/open-hack-xcm',
    Category: 'Open Hack Module',
    Level: 'Intermediate',
    Language: 'English',
    Source: 'OpenGuild',
    'Bundle Name': 'Substrate Course Bundle',
  },
  {
    'Course Name': 'Open Hack Chopstick',
    Status: 'In progress',
    'Third-party source': 'No',
    Link: 'https://github.com/openguild-labs/open-hack-chopstick',
    Category: 'Open Hack Module',
    Level: 'Intermediate',
    Language: 'English',
    Source: 'OpenGuild',
    'Bundle Name': 'Substrate Course Bundle',
  },
  {
    'Course Name': 'Open Hack ink! Advanced',
    Status: 'Done',
    'Third-party source': 'No',
    Link: 'https://github.com/openguild-labs/open-hack-ink-advanced',
    Category: 'Open Hack Module',
    Level: 'Intermediate',
    Language: 'English',
    Source: 'OpenGuild',
    'Bundle Name': 'Ink Course Bundle',
  },
  {
    'Course Name': 'Substrate Kitties',
    Status: 'Done',
    'Third-party source': 'No',
    Link: 'https://github.com/openguild-labs/substrate-kitties',
    Category: 'Course',
    Level: 'Intermediate',
    Language: 'English',
    Source: 'OpenGuild',
    'Bundle Name': 'Substrate Course Bundle',
  },
  {
    'Course Name': 'Parity Substrate DevOps Guide',
    Status: 'Done',
    'Third-party source': 'Yes',
    Link: 'https://paritytech.github.io/devops-guide/',
    Category: 'Documentation',
    Level: 'Advanced',
    Language: 'English',
    Source: 'Parity Tech',
    'Bundle Name': 'Substrate Course Bundle',
  },
  {
    'Course Name': 'Infrastructure DevOps Resources',
    Status: 'Done',
    'Third-party source': 'Yes',
    Link: 'https://forum.polkadot.network/t/infrastructure-devops-resources/1016',
    Category: 'Documentation',
    Level: 'Advanced',
    Language: 'English',
    Source: 'Polkadot Forum Post',
    'Bundle Name': 'Substrate Course Bundle',
  },
  {
    'Course Name': 'The Collator Setup Guide',
    Status: 'Done',
    'Third-party source': 'Yes',
    Link: 'https://hackmd.io/@s_iGZLIITG6WjSgnFX0pcg/the-collator-setup-guide',
    Category: 'Documentation',
    Level: 'Advanced',
    Language: 'English',
    Source: 'Daan van der plus',
    'Bundle Name': '',
  },
  {
    'Course Name': 'XCM Official Documentation',
    Status: 'In progress',
    'Third-party source': 'Yes',
    Link: 'https://paritytech.github.io/xcm-docs/',
    Category: 'Documentation',
    Level: 'Advanced',
    Language: 'English',
    Source: 'Parity Technologies',
    'Bundle Name': '',
  },
  {
    'Course Name': 'Polkadot SDK Docs - Enable metadata hash verification',
    Status: 'Done',
    'Third-party source': 'Yes',
    Link: 'https://paritytech.github.io/polkadot-sdk/master/polkadot_sdk_docs/guides/enable_metadata_hash/index.html',
    Category: 'Documentation',
    Level: 'Advanced',
    Language: 'English',
    Source: 'Parity Technologies',
    'Bundle Name': '',
  },
  {
    'Course Name': 'Polkadot SDK Docs - Enable storage weight reclaiming',
    Status: 'Done',
    'Third-party source': 'Yes',
    Link: 'https://paritytech.github.io/polkadot-sdk/master/polkadot_sdk_docs/guides/enable_pov_reclaim/index.html',
    Category: 'Documentation',
    Level: 'Advanced',
    Language: 'English',
    Source: 'Parity Technologies',
    'Bundle Name': '',
  },
  {
    'Course Name': 'Polkadot SDK Docs - Enable elastic scaling MVP for a parachain',
    Status: 'Done',
    'Third-party source': 'Yes',
    Link: 'https://paritytech.github.io/polkadot-sdk/master/polkadot_sdk_docs/guides/enable_elastic_scaling_mvp/index.html',
    Category: 'Documentation',
    Level: 'Advanced',
    Language: 'English',
    Source: 'Parity Technologies',
    'Bundle Name': '',
  },
  {
    'Course Name': 'Polkadot SDK Docs - Upgrade Parachain for Asynchronous Backing Compatibility',
    Status: 'Done',
    'Third-party source': 'Yes',
    Link: 'https://paritytech.github.io/polkadot-sdk/master/polkadot_sdk_docs/guides/async_backing_guide/index.html',
    Category: 'Documentation',
    Level: 'Advanced',
    Language: 'English',
    Source: 'Parity Technologies',
    'Bundle Name': '',
  },
  {
    'Course Name': 'Shawn Tabrizi - XCM Workshop',
    Status: 'Done',
    'Third-party source': 'Yes',
    Link: 'https://www.shawntabrizi.com/xcm-workshop/#/',
    Category: 'Course',
    Level: 'Advanced',
    Language: 'English',
    Source: 'Shawn Tabrizi',
    'Bundle Name': '',
  },
  {
    'Course Name': 'Learn JAM',
    Status: 'In progress',
    'Third-party source': 'No',
    Link: 'https://github.com/openguild-labs/learn-jam',
    Category: 'Aggregated Resource',
    Level: 'Advanced',
    Language: 'English',
    Source: 'OpenGuild',
    'Bundle Name': '',
  },
  {
    'Course Name': 'Substrate DPOS',
    Status: 'In progress',
    'Third-party source': 'No',
    Link: 'https://github.com/openguild-labs/substrate-nposdpos',
    Category: 'Course',
    Level: 'Advanced',
    Language: 'English',
    Source: 'OpenGuild',
    'Bundle Name': 'Substrate Course Bundle',
  },
  {
    'Course Name': 'Substrate NPOS',
    Status: 'In progress',
    'Third-party source': 'No',
    Link: 'https://github.com/openguild-labs/substrate-npos',
    Category: 'Course',
    Level: 'Advanced',
    Language: 'English',
    Source: 'OpenGuild',
    'Bundle Name': 'Substrate Course Bundle',
  },
].sort((ca, cb) => (cb['Course Name'] > ca['Course Name'] ? -1 : 1))
